::MAILER_PASSWORD = ENV['MAILER_PASSWORD'] || nil
::MAILER_DEFAULT_FROM = ENV['MAILER_DEFAULT_FROM'] || nil
::TWILIO_ACCOUNT_SID = ENV['TWILIO_ACCOUNT_SID'] || nil
::TWILIO_AUTH_TOKEN = ENV['TWILIO_AUTH_TOKEN'] || nil
::TWILIO_SENDER_NUMBER = ENV['TWILIO_SENDER_NUMBER'] || nil
::GOOGLE_ID = ENV['GOOGLE_ID'] || nil
::GOOGLE_SECRECT = ENV['GOOGLE_SECRECT'] || nil